keymanapp/help.keyman.com

products/linux/11.0/reference/km-package-install.php
manpage incorrectly says the switch `-k` for keyboard id.
Linux users confirm the switch should be `-p` for package ID.
e.g. `km-package-install -p sil_ipa`
=> Fix parameter for package ID

developer/11.0/guides/develop/tutorial/step-8.php
`index()` must match the `any()` at the third position; not the second.
=> Fix erroneous example

developer/12.0/context/keyboard-editor.php
Fixes #26
In the Touch Layout tab description, add a link to a guide for creating touch layouts.
The rest of the fix is covered in the keymanapp repo
=> Add link to guide for creating a touch layout keyboard

_includes/includes/head.php
This allows users to zoom in on content on the mobile site. Previously, the perspective and text sized was fixed, which made for bad user experience when, e.g., a users wants to zoom in on text or a particular image. This PR enables zoom in, while keeping the viewport looking correct on mobile browsers.
Related reading:
- http://adrianroselli.com/2015/10/dont-disable-zoom.html
- https://stackoverflow.com/a/22544312/6626414
- https://sitebulb.com/hints/mobile-friendly/the-viewport-meta-tag-prevents-the-user-from-scaling/
=> Allow users to zoom in on pages on mobile browsers

products/iphone-and-ipad/web.config
Allows iOS alpha versions to use the previous version's online help from non-existing alpha-version links.  See https://github.com/keymanapp/keyman/pull/2088 for reference.
=> Adds redirect for alpha iOS help links

_includes/includes/template.php, cdn/dev/js/kmlive.js
This PR's base (#51) temporarily disabled kmlive's form-factor autodetection given some of the changes to CSS.  This PR patches that (since #51's already approved) to re-enable it, but only when form-factor isn't specified by query.
This restores the default online auto-detect behavior of the page while still allowing the user to persistently set the form-factor if desired once the page is split into multiples.
=> Android help:  Re-enables non-embedded CSS autodetect

_includes/includes/session-embed.php, _includes/includes/session-formfactor.php, _includes/includes/template.php, cdn/dev/css/app-info-a.css, cdn/dev/css/formfactor.css, cdn/dev/js/kmlive.js, products/android/12.0/index.php
Before going further with the Android help page (by splitting it into multiple smaller pages), I felt it wise to focus on a simple redo of the existing page using CSS tricks.  Rather than maintain two separate tabs and performing wholesale "display: none" vs "display: block" operations, this uses CSS to toggle which image is displayed on the page in line with the surrounding text.
In all, this allows us to write the documentation on the page itself just the once, though of course there is all the PHP for image source links.
Note that this does temporarily break the ability to easily offline-mirror the page, but I've got a script near ready to handle that side of things (similar to the one introduced in https://github.com/keymanapp/keyman/pull/2102).
I'm still working on getting the …
=> Android main help page:  WET -> DRY with CSS

products/web/12.0/index.php
While the 11.0 section has more content, said content is a duplicate of the also-deprecated web/_`<`version`>`_/ui content - there's no reason to maintain it twice.  This leaves the Products > keymanweb.com section with a pretty small amount of content, but that's probably fine.
=> Basic keymanweb.com product page

_includes/includes/session-formfactor.php, products/android/12.0/index.php, products/android/12.0/installing-custom-keyboards.php, products/android/12.0/installing-keyboards.php, products/android/12.0/installing-system-keyboard.php, products/android/12.0/switching-between-keyboards.php, products/android/12.0/uninstalling-keyboards.php, products/android/12.0/using-keyman-browser.php
Completing the work started in #51 and #52, this PR splits the monolithic Android index.php into multiple smaller pages.  All content is still present; it's just that many bits have been relocated.
Aside from converting a lot of `<br>`s into `<p></p>` for more consistency in the formatting, very little content was actually edited here.
I debated on doing the `$embed_android` check for the form-factor banner within session-formfactor.php but settled on the current way for now, as that's a bit more general and reusable.
=> Android help - smaller, more focused pages

_includes/includes/phone-menu.php, _includes/includes/top-menu.php, developer/engine/android/web.config, developer/engine/desktop/10.0/api/index.php, developer/engine/desktop/10.0/index.php, developer/engine/desktop/web.config, developer/engine/iphone-and-ipad/web.config, developer/engine/web/web.config, developer/index.php, developer/keyboards/_shared/designing-keyboard.php, developer/keyboards/_shared/organize-include-exclude.php, products/android/web.config, products/desktop/web.config, products/iphone-and-ipad/web.config, products/linux/web.config, products/mac/web.config
Fixes #61
Per discussion with @mcdurdin , `/developer/engine/desktop/` links go to `10.0` with a small notice about the content applying to 11.0 and 12.0
=> Update primary links to 12.0

developer/12.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.php, developer/language/reference/layer.php
Fixes #86.
It was unclear which control took precedence when both `nextlayer` and
`layer` were in use in a keyboard. tl;dr: `nextlayer`.
=> fix: document layer switch precedence

developer/12.0/reference/file-types/index.php, developer/language/guide/constants.php
Fixes #87 adding file format details to https://help.keyman.com/DEVELOPER/12.0/reference/file-types/ 
Most of the individual file-type pages already listed file format details.
Also fixes documentation that named constants are **not** supported for characters above plane 0.
=> Add file types and fix constants documentation

developer/language/guide/constants.php
This was a misdiagnosis of an unrelated issue
as shown in keymanapp/keyman#2398.
Rolling back change applied in #89.
=> chore: rollback incorrect update to constants

knowledge-base/kb0069.md
Update a workaround for Keyman keyboard to type in Adobe Acrobat Reader.
Tests have been done for Keyman 8/9/10/11/12 to see if a Keyman keyboard can be typed in Adobe Acrobat Reader when the **Security (Enhanced)** is **ON**.
<table>
<tbody>
<tr><td>&nbsp;</td><td>8</td><td>9</td><td>10</td><td>11</td><td>12</td></tr>
<tr><td>Comment</td><td>v</td><td>v</td><td>v</td><td>v</td><td>v</td></tr>
<tr><td>Find</td><td>v</td><td>v</td><td>v</td><td>v</td><td>v</td></tr>
<tr><td>Fill & Sign</td><td>x</td><td>x</td><td>x</td><td>x</td><td>x</td></tr>
</tbody></table>
v: typable, x: not typable
=> [help.keyman.com] update kb0069

developer/language/reference/_index.php, developer/language/reference/_nul.php, developer/language/reference/any.php, developer/language/reference/baselayout.php, developer/language/reference/beep.php, developer/language/reference/begin.php, developer/language/reference/context.php, developer/language/reference/copyright.php, developer/language/reference/deadkey.php, developer/language/reference/ethnologuecode.php, developer/language/reference/group.php, developer/language/reference/if.php, developer/language/reference/keyboardversion.php, developer/language/reference/match.php, developer/language/reference/message.php, developer/language/reference/mnemoniclayout.php, developer/language/reference/name.php, developer/language/reference/nomatch.php, developer/language/reference/notany.php, developer/language/reference/outs.php, developer/language/reference/platform.php, developer/language/reference/reset.php, developer/language/reference/save.php, developer/language/reference/set.php, developer/language/reference/store.php, developer/language/reference/targets.php, developer/language/reference/use.php, developer/language/reference/version.php, developer/language/reference/visualkeyboard.php
Fixes #97
* Add Linux to the Developer support grids
* Clarify mnemonimc keyboards work on Mac, but cannot select a different base keyboard
* Mark `if()` as incomplete on Mac and Linux because options form is not supported
=> Clean up support details for Developer language

developer/12.0/context/keyboard-editor.php
'Display underlying' and 'Display 102nd key' are updated. Note this does not change the graphic but we'll do that in the 13.0 documentation run.
=> [Developer] Clarify details on keyboard editor

developer/language/reference/bitmap.php, developer/language/reference/call.php, developer/language/reference/caps.php, developer/language/reference/hotkey.php, developer/language/reference/includecodes.php, developer/language/reference/kmw_embedcss.php, developer/language/reference/kmw_embedjs.php, developer/language/reference/kmw_helpfile.php, developer/language/reference/kmw_helptext.php, developer/language/reference/kmw_rtl.php, developer/language/reference/language.php, developer/language/reference/layer.php, developer/language/reference/layout.php, developer/language/reference/layoutfile.php, developer/language/reference/return.php, developer/language/reference/windowslanguages.php
Addresses this comment on #11 
> Platforms sections in language reference need update for Linux.
and picking up after #98
=> Add linux to rest of Developer language reference tables

_includes/includes/head.php
I was having a few issues trying to investigate https://github.com/keymanapp/keyman/issues/2818.  This simple setup allows easily debugging situations like this with the website in the future by allowing tests to run against local builds (as hosted by a local webserver).
With this in place, simply uncomment line 9 and edit it to match your local setup so that it accesses a valid build product for KMW.
Note:  is based on #149 because it further edits some of the same code.  And #149 was referenced in https://github.com/keymanapp/keyman/issues/2818, anyway.
Also of note:  there's a lot of duplicated code between this and __kmwheader.php (another include), but sorting that out is likely a matter for another day.  This tweak was directly inspired by its setup.
=> feat: allows testing keyboard help pages with dev KMW

_includes/includes/head.php, cdn/dev/js/kbd-docs.js
This is a quick fix to get keyboard fonts working
on help pages; it relies on api.keyman.com,
s.keyman.com being in sync. In future we should
look at leveraging KeymanWeb's built-in font
support but that requires more re-engineering
of the help kbd-docs js.
Fixes #150.
=> fix: support keyboard fonts

developer/lexical-models/_shared/organize-folder-structure.php, developer/lexical-models/_shared/organize-include-exclude.php, developer/lexical-models/index.php
There were a few links pointing to 12.0 documentation for lexical models. I've updated them to use `current-version` so that they're always up-to-date.
=> fix: use /developer/current-version for LMLayer doc links

developer/14.0/guides/lexical-models/advanced/search-term-to-key.php
This updates the documentation for 14.0 to show the new default `searchTermToKey` function, which was merged in keymanapp/keyman#3024.
=> change(common/lmlayer): document new default search term to key fn

developer/13.0/context/model-editor.php, developer/14.0/context/model-editor.php, developer/14.0/guides/lexical-models/advanced/model-definition-file.php, developer/14.0/guides/lexical-models/advanced/word-breaker.php, developer/14.0/reference/file-types/model-ts.php
Note: I've made a few identical changes in the 13.0 and 14.0 docs, as they are applicable to both, however, the new syntax for the `wordBreaker` property, and the new default `searchTermToKey()` are only applicable to 14.0.
=> docs(common/lmlayer): tweak docs for word breaker and search term to key

_includes/includes/com.keyman.help.editpage.inc.php, _includes/includes/com.keyman.help.kb.inc.php, _includes/includes/footer.php, _includes/tests/com.keyman.help.editpage.test.php, knowledge-base/index.php
This also establishes a base namespacing scheme for PHP files to try and give some direction for future patches and changes to websites. `com\keyman\help` will be the long-term base namespace for help.keyman.com, with `com\keyman\help\kb` being the namespace for knowledge base. For now we still need to `require()` the include files because we need to make additional file layout changes for auto require patterns.
Feedback on the design appreciated. See PHP's [weird and wonderful namespace documentation](https://www.php.net/manual/en/language.namespaces.basics.php) for how it's supposed to all work.
=> fix: edit page link for kb articles

developer/engine/android/10.0/KMManager/getLatestKeyboardFileVersion.php, developer/engine/android/11.0/KMManager/getLatestKeyboardFileVersion.php, developer/engine/android/12.0/KMManager/getLatestKeyboardFileVersion.php, developer/engine/android/13.0/KMManager/getLatestKeyboardFileVersion.php
Starting with KMEA 10.0 onward, the syntax for getLatestKeyboardFileVersion() changed from
`getLatestKeyboardFileVersion(Context context, final String keyboardID)` to
`getLatestKeyboardFileVersion(Context context, final String packageID, final String keyboardID)`
This PR fixes:
* documentation to account for packageID
* the description on which paths are analyzed (cloud/ vs packages/)
=> fix(android): Fix syntax for getLatestKeyboardFileVersion

developer/engine/android/11.0/KMManager/getGlobeKeyAction.php, developer/engine/android/11.0/KMManager/setGlobeKeyAction.php, developer/engine/android/12.0/KMManager/getGlobeKeyAction.php, developer/engine/android/12.0/KMManager/setGlobeKeyAction.php, developer/engine/android/13.0/KMManager/getGlobeKeyAction.php, developer/engine/android/13.0/KMManager/setGlobeKeyAction.php
KMEA 11.0 added a globe action `GLOBE_KEY_ACTION_ADVANCE_TO_NEXT_SYSTEM_KEYBOARD`. This updates the get/set documentation
=> Add GLOBE_KEY_ACTION_ADVANCE_TO_NEXT_SYSTEM_KEYBOARD

developer/cloud/keyboard_info/1.0/index.php
This reverts a change in #36. The fields in question are still in use and are being generated by mergekeyboardinfo during compilation. See also corresponding api.keyman.com https://github.com/keymanapp/api.keyman.com/pull/59.
=> fix: revert 1.0.6 spec as fields still in use

developer/cloud/package-version/1.0/index.md
It wasn't clear whether package-version should be passed a
package id or a keyboard id.
=> fix: clarify identifiers for package-version

_includes/includes/servervars.php
This variable is used by keyboard documentation. It will still exist in `staging` but will use `KeymanHosts` there. It replaces legacy references to the tavultesoft site in the keyboard documentation, and thus will work on both `master` and `staging` branches.
=> chore: add keyman_com global

developer/14.0/guides/lexical-models/advanced/index.php, developer/14.0/guides/lexical-models/advanced/word-breaker.php
Documents `overrideScriptDefaults` customization for word breakers, introduced in https://github.com/keymanapp/keyman/pull/3506 (due to be released in Keyman 14.0)
=> docs: document overrideScriptDefaults

products/android/14.0/_shared/help_links.php, products/android/14.0/system-requirements.php
At @MakaraSok 's request, this adds a page about the system requirements to run Keyman for Android
Note, this applies to Keyman 14.0 which raises the minimum Android SDK from 4.4 KitKat to 5.0 Lollipop.
Also, the KMEA content for Keyman 14.0 already lists 
> Android 5.0  and layer versions
=> docs: Add page on Android System Requirements

developer/11.0/reference/file-types/kmx.php, developer/12.0/reference/file-types/kmx.php, developer/13.0/reference/file-types/kmx.php, developer/14.0/reference/file-types/kmx.php
Fixes #197
Starting with 11.0, Keyman for Linux also uses kmx.
=> fix: Update kmx usage

developer/language/guide/groups.php
Fixes #152.
Note that the [`group` reference page](https://help.keyman.com/developer/language/reference/group) includes this information as well.
=> Add 'using keys' notes

_includes/includes/page-version.php
Relates to #233.
The oldest version was selected instead of the newest version in one place, where other places expected the newest version, leading to broken links appearing on some pages, e.g. developer/cloud/1.0/webapi (note, this was appearing in the `<link rel=canonical>` tag, so not visible on the page).
=> fix: current-version breaking some links

.gitignore, products/linux/11.0/common.php, products/linux/12.0/common.php, products/linux/13.0/common.php
This mirrors the clarification to the Keyman for Linux architecture done in keymanapp/keyman.com#183
Other notes
* I only bothered fixing the typos in versions 11.0-12.0.
* Updated .gitignore to ignore the /vendor/ folder used on `staging`.
=> chore: Clarify linux architecture

.vscode/settings.json, _includes/includes/ext/parsedown/Parsedown.php, _includes/includes/ext/parsedown/ParsedownExtra.php, _includes/md/mdhost.php
This adds support for latest version of Parsedown to master branch and adds ParsedownExtra for support for additional features such as definition lists.
Will be used for content such as #242.
Throws in vscode styling while we are at it.
Note that this diverges from the work in staging branch (e.g. #256) because we do not use Composer yet in the master branch.
=> chore: update parsedown

developer/engine/android/14.0/KMManager/addKeyboard.php, developer/engine/android/14.0/KMManager/getCurrentKeyboardInfo.php, developer/engine/android/14.0/KMManager/getDefaultKeyboard.md, developer/engine/android/14.0/KMManager/getDefaultKeyboard.php, developer/engine/android/14.0/KMManager/getKeyboardInfo.php, developer/engine/android/14.0/KMManager/getKeyboardsList.php, developer/engine/android/14.0/KMManager/getMaySendCrashReport.md, developer/engine/android/14.0/KMManager/index.php, developer/engine/android/14.0/KMManager/setDefaultKeyboard.md, developer/engine/android/14.0/KMManager/setKeyboard.php, developer/engine/android/14.0/KMManager/setKeymanLicense.php, developer/engine/android/14.0/KMManager/setMaySendCrashReport.md, developer/engine/android/14.0/KMManager/showLanguageList.php
This starts to address #180
Add new KMManager API's
* getDefaultKeyboard()
* setDefaultKeyboard()
* getMaySendCrashReport() (See keymanapp/keyman#3825)
* setMaySendCrashReport()
Modifications
* Update the add/get/set Keyboard methods to use the new Keyboard type. (Mark HashMap dictionaries as *(Deprecated)*)
=> chore: Update KMEA KMManager for 14.0

knowledge-base/kb0101.md, knowledge-base/kb0102.md, knowledge-base/kb0103.md
- "Using Keyman for Linux with KDE" from community site
- "How to install IBus and Keyman on Arch Linux and derivatives" and "How to install nightly packages of Keyman for Linux" from Keyman wiki
Once this PR is merged we should replace the content of the original pages with links to the KB articles
=> Move howto pages

cdn/cdnrefresh.php
This change allows `cdnrefresh.php` to properly run on Linux.
=> chore(common): Improve cross-platform compatibility of cdnrefresh.php

_includes/includes/history_utils.php
Follow-on to #262 
The regex to tighten formatting needs to be applied to the entire history display. (Currently, help.keyman-staging is using `<h3>` for 14.0 history and `<h2>` for older history.
This also strips out the title when merging in older history.
Screenshot of developer/engine/web/historyhistory
=> chore: Use consistent headers between API versions

knowledge-base/kb0103.md, products/linux/14.0/common.php
Update the documentation for the renamed onboard package. The package name is now `onboard-keyman` instead of `onboard`.
Part of keymanapp/keyman#3966.
=> feat(linux): Rename onboard package

developer/keyboards/starter/index.php
Missed this one in the report last time.
=> fix: keyboard starter guide broken link

.github/workflows/ci.yml
The GitHub action runner [has been updated to 8.0.1](https://github.com/actions/virtual-environments/blob/releases/win19/20210110/images/win/Windows2019-Readme.md) but many of our dependencies do not currently support it without updates. For now, we will test on our supported version of PHP using the [setup-php action](https://github.com/marketplace/actions/setup-php-action), as recommended by https://github.com/actions/virtual-environments/issues/2416.
=> chore: github action php 7.4 dependency

developer/language/reference/caps.php
Caps lock isn't implemented yet on Linux ([#4542](https://github.com/keymanapp/keyman/issues/4542)).
=> docs(linux): Update documentation for caps lock

developer/language/guide/virtual-keys.md
Adds visual documentation of the virtual key layout:
*** note: updated graphic because original screenshot I had here was of an older iteration which had a typo.
Also:
* Two ISO codes were interchanged
* Adds `B11` for ABNT2 keyboard.
=> feat: add virtual key code visual chart

_common/MarkdownHost.php
This replaces the somewhat fragile regex with a simple line-based parser of the headers. Seems to be somewhat cleaner.
=> fix: markdown header parser was not parsing some headers

developer/engine/android/14.0/KMManager/getDefaultKeyboard.md, developer/engine/android/14.0/KMManager/getMaySendCrashReport.md, developer/engine/android/14.0/KMManager/index.php, developer/engine/android/14.0/KMManager/isKeyboardLoaded.md, developer/engine/android/14.0/KMManager/setMaySendCrashReport.md
Documents KMManager.isKeyboardLoaded() from keymanapp/keyman#4696
Also fixes some `###Parameters` and `### Returns` headers to nest under `## Syntax`
=> feat: add  isKeyboardLoaded

products/windows/14.0/TODO.md, products/windows/15.0/TODO.md
Fixes #375 by removing obsolete TODO.md files.
They were already removed in the main repo by keymanapp/keyman#4717 so hopefully they won't reappear when the help docs sync.
=> chore: Remove TODO files

developer/14.0/guides/lexical-models/advanced/model-definition-file.php
Fixes #327 by updating the link to the lexical-model interface to stable-14.0
=> chore: Update link to lexical-model interface

cdn/dev/js/kbd-docs.js
This is a problem for some browsers, e.g. Opera Mini. We don't use backtick widely so let's just remove it for now.
Fixes [HELP-KEYMAN-COM-10](https://sentry.keyman.com/organizations/keyman/issues/4254/), [HELP-KEYMAN-COM-15](https://sentry.keyman.com/organizations/keyman/issues/4283/).
=> fix: we should not use backtick in live code yet

developer/14.0/guides/lexical-models/tutorial/step-1.php
Fixes #392 adding a note about word breaking in the lexical-model prerequisites.
=> chore: Add note about word-breaking in lexical-model guide

.github/workflows/auto-merge-keyman-server-pr.yml
Addresses #332 for Action to auto-merge help PRs created during builds
I lifted this from the main repo, so `AUTOINC_GITHUB_TOKEN`might not be correct...
=> chore: Auto-merge help PRs created during builds

knowledge-base/kb0040.md
Fixes #409 
The path for Keyman for WIndows help images recently changed  - breaking the image links in the knowledge base article.
=> fix: Broken image links in knowledge base article

products/mac/15.0/about/whatsnew.md
For some reason this didn't get auto-merged
Update: @mcdurdin noted cause the build agent didn't have hub installed.
This content is also duplicated in auto/mac-help-15.0.69-alpha so we just need one of them.
=> auto: Keyman for mac help deployment

developer/engine/web/15.0/reference/core/init.php
This documents the added options flag `useAlerts` from keymanapp/keyman#5302. 
Also adds the missing option `setActiveOnRegister`
Most of the changes are from seeding the 15.0 KeymanWeb engine content, so I suggest reviewing the 3rd commit onward.
=> docs: Add KeymanWeb option flags useAlerts and setActiveOnRegister

developer/engine/web/15.0/reference/core/init.php
Follow-on to #420 
This updates the documentation of init options to reflect the direction given in keymanapp/keyman#5302
=> docs: Clarify init options

developer/engine/web/10.0/guide/adding-keyboards.php, developer/engine/web/11.0/guide/adding-keyboards.php, developer/engine/web/12.0/guide/adding-keyboards.php, developer/engine/web/13.0/guide/adding-keyboards.php, developer/engine/web/14.0/guide/adding-keyboards.php, developer/engine/web/15.0/guide/adding-keyboards.php
In keymanapp/keyman#528, Keyman Developer 10.0 no longer generates loader scripts for KeymanWeb keyboards.
> They use an old mode of loading a keyboard stub, rather than the current `addKeyboards` API
This cleans up the adding-keyboards guide for engine/web/10.0 onward.
=> chore: Remove usage of loader script

developer/engine/web/15.0/reference/core/addKeyboards.md, developer/engine/web/15.0/reference/core/addKeyboardsForLanguage.md, developer/engine/web/15.0/reference/core/index.php, developer/engine/web/15.0/reference/core/init.md, developer/engine/web/15.0/reference/keyboard_registration_errors.md
This documents the change from keymanapp/keyman#5044 where KeymanWeb async API calls now return a promise.
Also reverts initialization options `setActiveOnRegister` and `useAlerts` that were inadvertently dropped in #432 when `init.php` was migrated to `init.md`
=> feat: Document KeymanWeb API calls returning a promise

_includes/includes/head.php
A fix I made in #299 to stop search engines indexing the staging sites accidentally broke the link checker, by telling it to skip all links.
=> fix: link checker was skipping all links

knowledge-base/kb0107.md
This adds a knowledge base article on installing Keyman for macOS on an M1.
Reference
https://community.software.sil.org/t/does-keyman-support-m1-mac/5213
=> chore: Add kb article on installing for M1 Mac

cdn/dev/css/template.css
Fixes #261. Easiest way to fix was to remove the 600px stop which was inconsistent in its styling in any case.
=> fix: logo overlap on some sizes

knowledge-base/kb0107.md
Documents M1 support from keymanapp/keyman#5737
> Note: https://help.keyman.com/knowledge-base/107 needs to be updated once this and a cherry-picked to 14 version are released.
=> chore: Update kb article on Keyman for macOS on M1

developer/engine/android/15.0/KMManager/applyKeyboardHeight.md, developer/engine/android/15.0/KMManager/getKeyboardHeight.php, developer/engine/android/15.0/KMManager/index.php
Addresses comment
https://github.com/keymanapp/keyman/issues/3225#issuecomment-922562678
and documents the API `KMManager.applyKeyboardHeight()` added to Keyman Engine for Android from keymanapp/keyman#5606
=> docs: Document KMManager.applyKeyboardHeight()

knowledge-base/kb0097.md
From version 15 the seralized input pipline will not be active
if a Keyman keyboard is not active. Update the document to reflect this.
=> docs: updated info on seralised input behaviour

cdn/dev/js/kbd-docs.js, cdn/dev/js/kmlive.js
Relates to keymanapp/keyman#2750.
When you load a page with a `#toc-` hash, it would not scroll to the correct place in the document, because the `#toc-` anchors are all defined dynamically after page load.
This adds a slightly hacky fix to scroll the anchor into view, leveraging the existing toc elements to access the custom scroll code.
Note that this jquery code is all very old, but changing that is a much more significant update which needs site-wide consideration.
=> fix: help offset

developer/15.0/context/kmconvert.md
Fixes #527 
Documents the lexical-model parameters `-id-author` and `-id-uniq` to be tokens
=> chore: Document id-author and id-uniq

knowledge-base/kb0035.md
This applies only to building self-extracting installers...
=> docs: clarify setup.exe must be unsigned

_includes/includes/head.php
Will revert keymanapp/help.keyman.com#561, once keymanapp/keyman#6817 (`stable-15.0` 🍒 of keymanapp/keyman#6793) has been released.
=> chore: Revert temporary use of 14.0

knowledge-base/kb0103.md
Using apt-key is deprecated in Ubuntu 22.04+, resulting in an ugly warning when updating packages. This change documents the recommended way of adding a new key.
=> feat: Improve KB article

developer/engine/iphone-and-ipad/15.0/guides/system-keyboard/index.php
Fixes an issue noted at https://github.com/keymanapp/keyman/issues/7010 - problems arose for a user because 15.0 help referred to a 14.0 dependency file that was updated in 15.0.
=> fix: updated dependency link for ios engine

developer/keyboards/index.php
line 42: broken link <a href="https://help.keyman.com/keyboards/"   should it be    https://help.keyman.com/keyboard/    ?
=> broken link to help on keyboards 

developer/core/desktop/15.0/building.php, developer/core/desktop/15.0/c-api/context-api.php, developer/core/desktop/15.0/c-api/index.php, developer/core/desktop/15.0/c-api/keyboard-api.php, developer/core/desktop/15.0/c-api/option-api.php, developer/core/desktop/15.0/c-api/state-api.php, developer/core/desktop/15.0/index.php, developer/core/desktop/15.0/json-schema.php
This PR updates the help to be in line with the changes made to version 15 of the core API. 
Todo in a separate PR convert the help files to markdown.
=> docs(core): update core api for version 15

developer/core/desktop/web.config
As noted in https://github.com/keymanapp/help.keyman.com/pull/588/files#r949335322
The desktop engine content should redirect 12.0, 13.0 to 11.0 (not current-version).
=> fix: Desktop engine content between 11.0 and 13.0

.htaccess, _includes/errors/404.php
Follow-on to #588
On Apache, this passes the requested URI for 404 errors. (IIS still using REQUEST_URI)
afaict, Apache redirects ErrorDocument so the original code:
```
$page = $_SERVER["REQUEST_URI"]
```
was displaying the path to the 404.php page.
atm I don't know how to prevent the addressbar from updating
e.g.
http://localhost.8055/bogus results in
http://localhost:8055/_includes/errors/404?uri=/bogus
=> fix: Include requested URI on 404 error 🦭

build.sh
Follow-on to #604 
A couple quick fixes to the builder script:
* The start action needs to check for the docker image ID (not container)
* BASH: The _get_docker_*_id helpers need to echo a string instead of returning a numeric value.
* Fix typo in the OSTYPE check for Windows
=> fix: builder script for Windows 🦭

developer/cloud/index.md, developer/cloud/model/1.0/index.md, developer/cloud/model/index.md
Fixes #191.
Document `/model/id` and `/model/?q=` endpoints.
=> docs: model cloud API endpoints

Readme.md, resources/kubectl/help-kubectl-deploy.yaml, resources/kubectl/help-kubectl-dev.yaml, resources/kubectl/help-kubectl.yaml
This implements a deploy webhook by having a dedicated small responder directly perform a git pull. It turns out to be less trouble than watching for files in sidecar container, and more efficient than polling in a bash script signal files. This only maps the /api/deploy path to respond to GH push webhook events, leaving the rest of the '/api' space for the site's php. It is integrated to pull the secret from k8s a Secret volume (not defined here) and configuration (branch name to deploy, deploy script, and responder config) from k8s ConfigMap (included).
=> Add a /api/deploy endpoint for the k8s hosted site

developer/core/desktop/15.0/c-api/index.php, developer/core/desktop/16.0/c-api/index.php
Maybe fixes #668 
I don't see a section for `km_kbp_state` from the c-api page. Maybe it goes to `state-api#state`?
=> chore: Fix links to km_kbp_state

developer/core/desktop/15.0/c-api/context-api.php, developer/core/desktop/15.0/c-api/keyboard-api.php, developer/core/desktop/15.0/c-api/state-api.php, developer/core/desktop/16.0/c-api/context-api.php, developer/core/desktop/16.0/c-api/index.php, developer/core/desktop/16.0/c-api/keyboard-api.php, developer/core/desktop/16.0/c-api/option-api.php, developer/core/desktop/16.0/c-api/state-api.php
Fixes #671.
Fixes #670.
And restores 15.0 Core API documentation missing in 16.0.
=> docs: add parens and type clarifications to Core headings

keyboard/ipauni11/1.0/ipauni11.php
This is a :cherries: pick of 2b6ada9864dc4a4735d64cbaf17fa64633922564 which fixes the broken links to ofl.txt and ofl-faq.txt on the staging branch. Since the link-checker runs on a Linux host, the casing of OFL.txt and OFL-FAQ.txt matter.
These are help docs to legacy/i/ipauni11 so there's no changes needed in the keyboards repo.
Confession - I accidentally pushed 2b6ada9864dc4a4735d64cbaf17fa64633922564 straight to master branch of the help site, which has no effect cause master is still using IIS on a Windows host.
=> cherrypick: fix casing to OFL links 🍒

.github/workflows/ci.yml, .gitignore, Dockerfile, Readme.md, build.sh
Replaces #675
This is a second attempt to fix #674 and have the Docker file handle `composer install` so the dev environment doesn't need to have Composer installed.
Because of the way Docker handles filesystems, I had to move `build.sh configure` to link the `vendor/` folder after the container is running.
Previous attempts to copy `vendor/` to `/var/www/html/` don't work because the when the container starts, it replaces the folder with what's on the host (which doesn't have a `vendor/` folder)
Updates inspired from 
* [medium.com post](https://medium.com/@lukaspereyra8/docker-compose-php-composer-the-missing-vendors-folder-issue-66faa5475c59)
* [web-languageforge](https://github.com/sillsdev/web-languageforge/blob/ba4bf1ae838e48b4f2c2d7fa9861a7727eb04362/docker/app/Dockerfile#L38-L47) …
=> Remove dev requirement for Composer [Take 2]

.github/workflows/ci.yml, build.sh
Follow-on to #681 
@mcdurdin pointed out `./build.sh configure` should occur before `./build.sh start`.
So this moves the link step from `configure` to the end of `start`.
This way Docker maps the local folder first, and creating the link to vendor/ stays.
Will propagate this change to other websites and update keymanapp/keyman#8034
=> fix: Move link of vendor/ from build.sh configure to start 🦭

resources/kubectl/help-kubectl-deploy.yaml, resources/kubectl/help-kubectl-dev.yaml, resources/kubectl/help-kubectl.yaml
We want this so a k8s cluster can automatically migrate a workload to another node, perform rolling upgrades and scale instances up or down. A bare pod is not really the right way to deploy outside prototyping.
Also
1. Reduce the number images we depend on for sidecar/init containers to just alpine, for a smaller foot print and smaller supply chain attack surface.
2. Move specification of which files in the repo to include/exclude in the document root out of the init container shell script and into a ConfigMap entry for easier maintenance and clarity.
=> K8s convert pod to deployment

web.config
@jahorton noticed https://help.keyman.com/DEVELOPER/ENGINE/WEB/current-version/ was still going to 15.0 content.
Now that 16.0 is released, this updates `current-version` from 15.0 to 16.0.
Note: staging branch will need the corresponding change in `.htaccess`
=> chore: Update current-version to 16.0

knowledge-base/kb0095.md
When I tried to use cask as a command like this used to direct us to, I got the message:
Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.
=> cask is now option, not command

developer/engine/web/17.0/guide/adding-keyboards.php, developer/engine/web/17.0/guide/examples/__auto-control.php, developer/engine/web/17.0/guide/examples/__control-by-control.php, developer/engine/web/17.0/guide/examples/__first-example.php, developer/engine/web/17.0/guide/examples/__full-manual-control.php, developer/engine/web/17.0/guide/examples/__manual-control.php, developer/engine/web/17.0/guide/get-started.php
Follow-on to #710 
Updates more references from `kmw` to `keyman` in the 17.0 code examples.
=> chore: Update references to kmw in examples

.github/workflows/ci.yml
Fixes #711 
TODO: deprecated npm packages
=> chore: Update GHA to use node 16

keyboard/gff_harari/1.0.1/gff_harari.php, keyboard/gff_tigre/1.0/gff_tigre.php, keyboard/gff_tigrinya_eritrea/2.0/gff_tigrinya_eritrea.php
Fixes #729.
Note that gff_tigre and gff_tigrinya_eritrea will be overwritten by next keyboards deploy (gff_harari is now on 1.0.2 so 1.0.1 will never be rewritten by keyboards deploy again). So see keymanapp/keyboards#2255 for permafix for those two keyboards.
Am applying the fix here anyway so we can get green lights on CI, making sure nothing else is wrong.
=> chore: fix broken links in gff help

_common/KeymanHosts.php
This follows the sites-wide direction to use .localhost instead of .local for local Dev-hosted sites.
Mirrors keymanapp/keyman.com@3c9abe14fbb49d19bd3082081cfaf3ecf00cd82b
=> fix: Use .localhost instead of .local 🦭

.github/workflows/ci.yml, .gitignore, .htaccess, _includes/header.php, _includes/includes/head.php, _includes/includes/kb_doc_template.php, build.sh, cdn/dev/css/template.css, keyboard/index.php, resources/init-container.sh
* Fixes #824: adds a /keyboard/name/current-version canonical link
* Fixes #19: separates out deprecated keyboards and lists them later
* Also improves performance of keyboard index page, caching on first use.
=> chore: canonical keyboard version documentation

.gitattributes
I was trying to run the help site on a Windows host machine and ran into
```bash
/usr/bin/env: 'bash\r': No such file or directory
```
I think this got it working for me.
=> chore: Set line endings for .sh files

developer/17.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
Documents the non-printing characters added in 17.0 to:
* Developer keymanapp/keyman#9846 
* KeymanWeb keymanapp/keyman#9547 (keymanweb-osk.ttf) 
with the [font-symchar v4.0](https://github.com/silnrsi/font-symchar/blob/main/documentation/encoding.md).
At some point, maybe we move this entire table out of the guide into a kb article? I find it very hard to locate the special symbols :confused:
=> chore: Update "Key text" table for keymanweb-osk.ttf v4.0

developer/language/reference/_index.php
The sample previously used stores that weren't defined.
=> fix: Fix sample for index()

_control/info.php, test.php
Relates to keymanapp/keyman.com#403
=> chore: provide tier info in _control/info 🦭

developer/engine/android/17.0/KMManager/copyHTMLBannerAssets.md, developer/engine/android/17.0/KMManager/index.php, developer/engine/android/17.0/KMManager/setHTMLBanner.md
This documents the KMManager API calls added for controlling the Android HTML banner in keymanapp/keyman#9696
* KMManager.copyHTMLBannerAssets()
* KMManager.setHTMLBanner()
=> chore: Add docs for Android HTML banner

keyboard/cs-pinyin/1.3/cs-pinyin.php
Fixes #910 
Removing the page style fixes the help.keyman logo (tested on staging branch)
Not changing the keyboards repo because cs-pinyin is a legacy keyboard.
=> fix: Simplified Chinese help page styling

developer/engine/android/16.0/index.php, knowledge-base/kb0033.md
The link was pointed to 14.0 but titled as 15.0
=> Changing the link in /developer/engine/android/16.0 "See also" section 

developer/engine/web/15.0/guide/get-started.php, developer/engine/web/16.0/guide/get-started.php, developer/engine/web/17.0/guide/get-started.php
Fixes a mismatch between the language codes actually used by an example and what the example _says_ the codes are.  Obviously, in favor of the former.
=> fix: replace old-style lang codes, matching actual use

build.sh
Follows #976 
Handle this bullet point from keymanapp/keyman.com#403
> merge v0.4, new tag, update all dep sites to use the tag
for production branch
=> cherrypick: Update production to use shared-sites v0.4

.htaccess, _includes/errors/404.php
The .php extension on the 404 ErrorDocument directive was causing Apache to do a redirect. Removing this means that the original url is maintained.
Also did a little bit of cleanup to the error page at the same time:
* removed (unhelpful) breadcrumbs
* gave a direct link to Keyman Community
* removed IIS-specific code
=> chore: no redirect for 404

knowledge-base/kb0112.md
The steps to install a keyboard and then enable it for non-admin users or even each user on the local machine is not documented. This knowldege base article addresses that.
=> docs(windows): add knowledge base article for distributed keyboard installation

products/windows/.htaccess
Fixes #1033 adding /products/windows/14.0/docs redirects
There's still a long list that Google flagged - TODO for another day.
=> fix: products/windows/14.0/docs redirects

developer/17.0/guides/distribute/tutorial/step-2.php
Fixes #895.
The documentation needs more comprehensive work; this is addressing a single issue around creating vs using fonts, with minor tweaks on the same page.
=> docs(developer): tweak content around fonts

developer/core/desktop/17.0/background.md, developer/core/desktop/17.0/building.md, developer/core/desktop/17.0/changes.md, developer/core/desktop/17.0/index.md, developer/core/desktop/17.0/json-schema.md, developer/core/desktop/17.0/keyboards.md, developer/core/desktop/17.0/options.md, developer/core/desktop/17.0/processor.md, developer/core/desktop/17.0/state.md
Relates to keymanapp/keyman#10986, keymanapp/keyman#10580.
The files json-schema.md and building.md are local to this repo. The remainder are generated from keyman repo, keyman_core_api.h by api-header-extractor, and manually copied in from core/build/doc.
In the future, we need to move json-schema.md and building.md into the keyman repo as well, and generate the whole folder.
Also in the future we need to eliminate refs to Keyman Core Web and move this entire structure up a level, as it's just "Keyman Core" now, not "Keyman Core Desktop".
---
Note: the future tasks are tracked in https://github.com/keymanapp/keyman/issues/11029.
=> docs(core): add 17.0 docs

.htaccess, _includes/includes/index-content.php, _includes/includes/page-version.php
This aligns with the work on kmn.sh for error message redirects from kmc.
See also keymanapp/keyman#10888.
=> chore: support `latest-version` url format

developer/18.0/index.md, developer/18.0/reference/index.md
Note: only including index and reference folders so that we can merge automatic PRs for kmc api and clean the PR queue.
This is not a full 18.0 documentation seed, which should wait until 17.0 documentation refresh is complete.
=> chore: seed Developer 18.0 documentation

developer/17.0/reference/file-types/keyman-touch-layout.md
Fixes #805.
Copies the reference material out of the 'creating a touch layout' guide into the keyman-touch-layout reference page. Future refactor may involve rewriting the guide to remove the duplication.
=> docs(developer): copy touch layout reference material

developer/engine/android/17.0/KMManager/copyHTMLBannerAssets.md, developer/engine/android/17.0/KMManager/setHTMLBanner.md
(edit)
~Goes with keymanapp/keyman#11078 about updating the descriptions on Keyman Engine for Android HTMLBanner APIs.~
keymanapp/keyman#11078 replaced by keymanapp/keyman#11108, so this PR
~Also~ fixes the titles so they're in the same hierarchy as all the other KMManager pages.
=> chore: Fix titles about HTMLBanner

keyboard/gff_blin/1.1/gff_blin.php, keyboard/gff_blin/1.2/gff_blin.php, keyboard/gff_blin/1.3/gff_blin.php, keyboard/gff_blin/1.4.1/gff_blin.php, keyboard/gff_blin/1.4.2/gff_blin.php, keyboard/gff_blin/1.4/gff_blin.php, keyboard/gff_blin/1.5.1/gff_blin.php, keyboard/gff_blin/1.5.2/gff_blin.php, keyboard/gff_blin/1.5/gff_blin.php, keyboard/gff_gurage/0.6.1/gff_gurage.php, keyboard/gff_gurage/0.6.10/gff_gurage.php, keyboard/gff_gurage/0.6.11/gff_gurage.php, keyboard/gff_gurage/0.6.12/gff_gurage.php, keyboard/gff_gurage/0.6.2/gff_gurage.php, keyboard/gff_gurage/0.6.9/gff_gurage.php, keyboard/gff_gurage/0.6/gff_gurage.php, keyboard/gff_gurage/0.7/gff_gurage.php, keyboard/gff_gurage/0.8.1/gff_gurage.php, keyboard/gff_gurage/0.8/gff_gurage.php, keyboard/gff_gurage/0.9.1/gff_gurage.php, keyboard/gff_gurage/0.9/gff_gurage.php, keyboard/gff_gurage_legacy/0.1/gff_gurage_legacy.php, keyboard/gff_gurage_legacy/0.11/gff_gurage_legacy.php, keyboard/gff_tigre/1.0/gff_tigre.php, keyboard/gff_tigrinya_eritrea/1.1/gff_tigrinya_eritrea.php, keyboard/gff_tigrinya_eritrea/1.2/gff_tigrinya_eritrea.php, keyboard/gff_tigrinya_eritrea/1.3.1/gff_tigrinya_eritrea.php, keyboard/gff_tigrinya_eritrea/1.3.2/gff_tigrinya_eritrea.php, keyboard/gff_tigrinya_eritrea/1.3/gff_tigrinya_eritrea.php, keyboard/gff_tigrinya_eritrea/2.0/gff_tigrinya_eritrea.php
Follows #1209 
This removes the htmlentities used in `$pagetitles`
=> fix: More htmlentities in $pagetitles

developer/engine/iphone-and-ipad/16.0/LanguageResource/index.md
=> fix: misformatted links for iOS engine LanguageResource page

cdn/dev/js/kbd-docs.js
`keyman.options` was not a published API so there was no guarantee of stability. It changed to `keyman.config.options` in 17.0. Note: this is not a published API either.
Fixes: keymanapp/keyman#11466
Fixes: HELP-KEYMAN-COM-BWG
=> fix: keyman.options has become keyman.config.options

cdn/dev/js/kbd-docs.js
Fixes https://github.com/keymanapp/keyman/issues/11466.
Reworks #1265.
Uses a pre-existing published API: https://help.keyman.com/developer/engine/web/17.0/reference/util/getOption
=> fix: should use published API for KMW option access

.github/workflows/auto-approve-and-merge-keyman-server-pr.yml, .github/workflows/ci.yml, .github/workflows/docker.yml
While investigating the failed CI build on 
https://github.com/keymanapp/help.keyman.com/actions/runs/9009359924
I noticed the GHA notice:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.5.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
checkout 4.1.0 updates default runtime to node20
=> ci: Update GHA checkout to 4.1.5

_includes/errors/404.php, _includes/includes/page-version.php
Fixes: #1058
Case 1:
Case 2:
The content can only be found if the URL is using the structure: basePath + versionedPath + subPath. If found, the version switcher will show as the Version. If not, it will direct you to the home page. 
Please kindly review.
=> feat: include the version switcher in the errors page and show where the URL's subpath is located across the versions' folders

developer/engine/android/18.0/KMManager/getOrientation.md, developer/engine/android/18.0/KMManager/getWindowDensity.md, developer/engine/android/18.0/KMManager/getWindowSize.md, developer/engine/android/18.0/KMManager/index.md
Follows #1268 and documents Keyman Engine for Android 18.0 API's added from keymanapp/keyman#11436
* getOrientation() (added in 17.0 on keymanapp/keyman#10442 )
* getWindowDensity()
* getWindowSize()
TODO. Document some more API's from previous releases
* lexicalModelExists()
=> docs: Add getOrientation, getWindowDensity, and getWindowSize APIs

cdn/dev/css/template.css, developer/17.0/context/new-ldml-project-parameters.md, developer/17.0/context/package-editor.md, developer/17.0/context/server.md, developer/17.0/reference/kmc/cli/reference.md, developer/17.0/reference/user-settings.md, developer/cloud/model/1.0/index.md, developer/cloud/model/index.md, developer/cloud/version/2.0/index.md, developer/engine/web/15.0/reference/keyboard_properties.md, developer/engine/web/16.0/reference/keyboard_properties.md, developer/engine/web/17.0/reference/keyboard_properties.md, developer/language/reference/baselayout.md
* removes dot point so definition lists render correctly in kmc reference
* tweaks styling for code blocks in headings - background, font size
=> chore: cleanup definition lists and styling

build.sh
Update BOOSTRAP_VERSION to 0.8 to incorporate fix from keymanapp/shared-sites#20
=> chore: Update BOOTSTRAP_VERSION to 0.8

knowledge-base/kb0114.md
Addresses #94 on helping Linux users migrate from KMFL to Keyman for Linux
First commit was @ermshiperete 's answer on the [community site forum](https://community.software.sil.org/t/how-to-install-an-kmn-source-kmfl-file-onto-ubuntu-24-04/8864/5) (same response on Linux-user group.
Additional commits for formatting, and tweaking the section about a kmc compilation error.
=> Add KB article on migrating from KMFL to Keyman for Linux

developer/keyboards/github/step-0.md, developer/keyboards/github/step-2.md
This pull request adds information about how to access shared fonts when using the GitHub UI to submit a keyboard.
In addition, some references to obsolete files have been removed.
=> Add information on shared fonts

_includes/includes/head.php, cdn/dev/css/template.css, cdn/dev/js/kbd-docs.js
Reverts: keymanapp/help.keyman.com#1518
Fixes: keymanapp/keyman#12345
Co-authored-by: @ermshiperete 
Alongside additional CSS fixes:
1. Remove unnecessary font-size hammers for the OSK as KMW does a good job of managing font size itself now
2. Remove unnecessary `z-index: -2` for OSK that blocked interaction with earlier versions of KMW, as KMW documentation keyboards are no longer interactive
=> chore: Revert "chore: Revert "change: use published Keyman Engine API to fetch keyboards in keyboard help pages""

developer/engine/web/faq.php
Partially fixes: https://github.com/keymanapp/keyman.com/issues/415:
Google console reported an 404 link in this page (https://help.keyman.com/developer/engine/web/faq).
=> chore: switch to a usable link

developer/17.0/guides/lexical-models/tutorial/step-3.md
Request from Jeff Heath (author of PrimerPrep):
```
I noticed on https://help.keyman.com/developer/current-version/guides/lexical-models/tutorial/step-3 
that it points to lingtransoft.info for the PrimerPrep installation. 
That link should just point to https://software.sil.org/primerprep/ and/or 
https://software.sil.org/primerprep/downloads/.
Also the next line can be toned down a bit, maybe:
Run PrimerPrep (note that the first run might be slow; subsequent starts are faster)
```
=> Update PrimerPrep URLs

developer/engine/android/18.0/KMManager/getLongpressDelay.md, developer/engine/android/18.0/KMManager/index.md, developer/engine/android/18.0/KMManager/sendOptionsToKeyboard.md, developer/engine/android/18.0/KMManager/setLongpressDelay.md
Documents Keyman Engine for Android 18.0 API changes for keymanapp/keyman#12170 and keymanapp/keyman#12185
* getLongpressDelay
* sendKeyboardOptions
* setLongpressDelay
=> docs: Update API's for adjusting Android longpress delay

build.sh, resources/init-container.sh
Mirrors keymanapp/keyman.com#471 to skip generating CDN if `./build.sh --debug`
This uses `BOOTSTRAP_VERSION v0.10` so the optional debug parameter is passed to init-container.sh
=> fix: Skip CDN for --debug builds

cdn/dev/css/keyboard.css
A more comprehensive fix would need to be made to KeymanWeb, but that should be part of a more systematic review of KeymanWeb's CSS in the future.
Fixes: #1548
=> fix: override KeymanWeb CSS for z-index for documentation OSK

_includes/header.php, _includes/includes/head.php, _includes/includes/kb_doc_template.php, _includes/includes/template.php
Relates to keymanapp/keyman.com#383
This allows PHP pages to include `$language` in the headers to set the HTML lang attribute.
Markdown files would be handled by keymanapp/shared-sites#37 (lang or language?)
I tested locally by manually adding 
```php
'language' => 'th',
``` 
in https://github.com/keymanapp/help.keyman.com/blob/fb354f0a0db9989cbe2caed4492f897ff4f3fdcb/index.php#L7-L12
----
A keyboard help page would add
```php
$language = 'my';
```
to https://github.com/keymanapp/help.keyman.com/blob/fb354f0a0db9989cbe2caed4492f897ff4f3fdcb/keyboard/sil_myanmar_my3/1.7.3/sil_myanmar_my3.php#L1-L5
=> feat: Add optional `language` header to set HTML lang attribute 📓

_includes/includes/kb_doc_template.php
This is out of the F3: Hackathon module during the Keyman team meetings in CNX Nov 2024.
Doug Higby suggested for improving keyboard SEO that pages:
> Need keywords in both title and H1 
This changes the keyboard title from h2 to h1
=> feat(seo): change keyboard help page title from h2 to h1

.htaccess, keyboard/redir.php
Also removes the filter for file.php vs file/ conflict as I verified that there are no impacted folders. There are a few places where there is a xxx.php and a xxx/ folder, but none of them are problematic:
```
./developer/14.0/guides/develop/imx/web.php ==> ./developer/14.0/guides/develop/imx/web
./developer/15.0/guides/develop/imx/web.php ==> ./developer/15.0/guides/develop/imx/web
./developer/16.0/guides/develop/imx/web.php ==> ./developer/16.0/guides/develop/imx/web
./keyboard/khmer_angkor/1.0.5/khmer_angkor.php ==> ./keyboard/khmer_angkor/1.0.5/khmer_angkor
./keyboard/khmer_angkor/1.0.6/khmer_angkor.php ==> ./keyboard/khmer_angkor/1.0.6/khmer_angkor
./keyboard/khmer_angkor/1.0.7/khmer_angkor.php ==> ./keyboard/khmer_angkor/1.0.7/khmer_angkor …
```
=> fix: remove .php extension when redirecting URLs in /keyboard

build.sh
Addresses the :fire: in GFMAlerts from https://github.com/keymanapp/shared-sites/pull/50
=> chore: shared sites v0.14

keyboard/burushaski_girminas/2.0.24/burushaski_girminas.php, products/android/10.0/index.php
Part of: https://github.com/keymanapp/keyman.com/issues/415.
Info:
These links were returning 404 Not Found even though the content exists.
=> fix: 404 Not Found link in docs

cdn/dev/js/kbd-docs.js
Also adds a console.error catch() reporter so we don't get unhandled promise rejections in the event that the keyboard fetch fails for any reason.
Fixes: keymanapp/keyman#13043
=> fix: prevent KeymanWeb load of keyboards that do not have .js versions

developer/cloud/search/1.0/index.php, developer/cloud/search/2.0/index.md
A report on Google Search Console:
The URL is being used on these pages: 
- https://help.keyman.com/developer/cloud/search/1.0/
- https://help.keyman.com/developer/cloud/search/2.0/
The Changes:
=> chore: fixes Blocked due to other 4xx issue in Google Search Console

developer/language/reference/_index.md, developer/language/reference/_nul.md, developer/language/reference/context.md
Breaking documentation change: removes the distinction that was listed for `context(n)` offset calculations; see keymanapp/keyman#13299 for details.
Cleanup `context`, `index`, and `nul` documentation as well, tidy up some examples.
Fixes: #1888
=> docs(developer): clarify `context()` offset with `nul` and `if()`

developer/keyboards/phphelpfile.md
My previous revision instructed to delete `<html>` tag and its closing tag along with all of its contents. That technically means deleting the entire document. This rewording corrects that.
=> Slight tweak to phphelpfile.md

products/windows/.htaccess
Reported from Google Search Console.
=> fix: prepend slash to broken redirect in Windows 14 docs

robots.txt
Staging site getting hammered by an Amazon bot causing an OOM bootloop
@mcdurdin recommends we disallow all bots since the staging site doesn't need to be indexed.
=> fix: Disallow all bots since staging site doesn't need to be indexed

_includes/includes/head.php
In the Development tier, if the other ancillary Keyman sites aren't running, then the site will fetch this fallback version of KeymanWeb from s.keyman.com
The previous version '13.0.108' doesn't render the keyboard layouts
=> chore: Update fallback version of KeymanWeb to 18.0.235

_includes/includes/com.keyman.help.editpage.inc.php
The footer link to edit product help pages is broken.
Comes out of the refactor from keymanapp/keyman#12424
which renamed the folders to the product help.
TODO (separate PR?):
https://github.com/keymanapp/help.keyman.com/blob/4e6fb0ac55572fea57e66d563e8702622a990b85/_includes/includes/com.keyman.help.editpage.inc.php#L30-L65
Fixes: #1999
=> fix: Update links to edit product help files

developer/language/reference/if.md
While discussing [#13492](https://github.com/keymanapp/keyman/pull/13492) we discovered that the comparison with a store was never implemented. This change fixes the documentation to match reality.
Test-bot: skip
=> fix: remove documentation for never implemented feature of `if`

cdn/dev/css/template.css
Before:
http://help.keyman.com.localhost:8055/keyboard/wali/1.0/wali#toc-touch-keyboard-layouts
After: 
Test-bot: skip
=> style: fix osk-phone images for keyboard help pages
