keymanapp/help.keyman.com

- products/linux/11.0/common.php
Update Keyman for Linux install instructions to match sillsdev/keyman-keyman.com#249
> Update Keyman for Linux install instructions

- products/mac/11.0/docs/index.php
- products/mac/11.0/docs/start_download-install_keyman.php
Clarify the steps for installing and updating Keyman for macOS
> Update mac documentation

- developer/language/reference/if.php
- developer/language/reference/reset.php
- developer/language/reference/save.php
- developer/language/reference/set.php
> Update documentation on support for if/set/save/reset for macOS

- developer/12.0/context/index.php
- developer/12.0/context/kmcomp.php
- developer/12.0/context/kmlmc.php
- developer/12.0/context/kmlmi.php
- developer/12.0/context/kmlmp.php
* kmcomp - Add color parameters (keymanapp/keyman#2128)
* add kmlmc, kmlmp, kmlmi
> Add 12.0 updates for Developer command-line tools

- developer/engine/iphone-and-ipad/12.0/Manager/downloadKeyboard.php
- developer/engine/iphone-and-ipad/12.0/Manager/downloadLexicalModel.php
- developer/engine/iphone-and-ipad/12.0/Manager/index.php
- developer/engine/iphone-and-ipad/12.0/Manager/keyboardHeight.php
- developer/engine/iphone-and-ipad/12.0/Manager/parseKMP.php
- developer/engine/iphone-and-ipad/12.0/Manager/stateForLexicalModel.php
This is based on #58 and serves to enhance the documentation for already-published API and any closely-paralleled new API for lexical models.
This assumes that https://github.com/keymanapp/keyman/pull/2165 will be merged in its current state, so it may need updates if big changes are requested there.
> [iOS] KMEI - API Reference update

- developer/cloud/version/2.0/index.php
Documents the change from keymanapp/api.keyman.com#17
> Add linux to api.keyman.com/version documentation

- products/web/web.config
> fix: Redirect unversioned web link to 12.0

- developer/language/reference/hotkey.php
Documentation update for keymanapp/keyman#2432.
> feat(developer): unquoted hotkeys

- developer/cloud/keyboard_info/1.0/index.php
- developer/cloud/search/1.0/index.php
Documentation relating to keymanapp/api.keyman.com#28 and keymanapp/keyman.com#62.
> fix: deprecated keyboard search

- _includes/includes/footer.php
- cdn/dev/css/kmdist.css
- cdn/dev/css/template.css
- cdn/dev/js/kbd-docs.js
Provides a quick link to the GitHub editor
for the page in question. Hope that this
streamlines quick edits to help pages and
encourages minor fixes by us and others.
> feat: edit page link

- developer/10.0/guides/develop/touch-keyboard-tutorial/index.php
- developer/11.0/guides/develop/touch-keyboard-tutorial/index.php
- developer/12.0/guides/develop/touch-keyboard-tutorial/index.php
> Fix broken links to 'Quick French Tutorial'

- _includes/includes/footer.php
Addresses updating the privacy policy for keymanapp/keyman.com#41
Are all the current EULA verbage fine sticking with MIT license?
e.g. https://help.keyman.com/products/desktop/13.0/docs/about_license
> Update link to SIL privacy policy

- developer/language/guide/groups.php
- developer/language/guide/stores.php
- developer/language/reference/reset.php
- developer/language/reference/save.php
- developer/language/reference/set.php
- developer/language/reference/store.php
Some suggestions for adjusting sample code
> Inkeysoftware patch 1

- developer/13.0/reference/file-types/index.php
- developer/13.0/reference/file-types/ttf.php
> Add ttf file type

- developer/13.0/guides/lexical-models/advanced/search-term-to-key.php
I added wording that makes it explicit that `searchTermToKey()` happens both at compilation and on the input; and I added some suggested customizations.
> [LMLayer] More documentation on search-term-to-key

- knowledge-base/kb0095.md
Added draft of kb0095.md - HOWTO: Installing KMComp Command Line Compiler on MacOS Catalina
> Draft of kb0095.md - HOWTO: Installing KMComp on MacOS Catalina

- developer/videos.md
Videos are now available per topic as well as full-session.
> feat: add new videos from Developer workshop

- knowledge-base/kb0096.md
"Using" is missing in the second paragraph.
> correct a typo

- developer/14.0/guides/lexical-models/advanced/word-breaker.php
Documents how to customize word breaking with `joinWordsAt:` property.
Depends on:
- keymanapp/keyman#3021
- keymanapp/keyman#3032
~~Closes~~ Addresses: keymanapp/keyman#2753
> docs: document wordBreaker joinWordsAt property

- _includes/includes/com.keyman.help.editpage.inc.php
> fix: edit page link was crashing for kb articles

- knowledge-base/kb0035.md
- knowledge-base/kb0098.md
> feat: kmshell and setup command line options

- _includes/autoload.php
- _includes/includes/servervars.php
- _includes/includes/template.php
- _includes/kmdevhtml.php
- _includes/servervars.php
- developer/engine/web/1.0/content/troubleshooting/embedded_fonts.php
- keyboard/ekwunitamil/1.0/ekwunitamil.php
Fixes #196.
Note, not every error has been addressed from the issue. There are a few which are less obvious and for which I will wait until we start to get Sentry reports for them.
> fix: various site errors

- .gitignore
- Readme.md
- _common/KeymanHosts.php
- _common/KeymanSentry.php
- _common/README.md
- _includes/autoload.php
- _includes/includes/servervars.php
- _includes/includes/template.php
- _includes/kmdevhtml.php
- _includes/servervars.php
- composer.json
- composer.lock
- developer/engine/web/1.0/content/troubleshooting/embedded_fonts.php
- keyboard/ekwunitamil/1.0/ekwunitamil.php
Adds reporting to sentry.keyman.com for site
errors. Adds composer as preferred method for
integrating sentry.
> feat: sentry integration (and common files)

- developer/cloud/search/1.0/index.php
- developer/cloud/search/2.0/index.md
Relates to keymanapp/api.keyman.com#87
> feat: cloud search 2.0 documentation

- developer/engine/desktop/14.0/api/IKeymanBCP47Canonicalization/GetCanonicalTag.php
- developer/engine/desktop/14.0/api/IKeymanBCP47Canonicalization/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardFile2/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled/Install.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/FindInstallationLangID.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/InstallTip.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/IsRegistered.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/RegisterTip.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguageInstalled2/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/Install.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/InstallByLangID.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled2/Add.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardLanguagesInstalled2/index.php
- developer/engine/desktop/14.0/api/IKeymanKeyboardsInstalled2/index.php
- developer/engine/desktop/14.0/api/IKeymanPackageFile2/index.php
- developer/engine/desktop/14.0/api/IKeymanPackagesInstalled2/index.php
- developer/engine/desktop/14.0/api/__interface-hierarchy.php
Relates to keymanapp/keyman#3512.
> docs: new kbd language methods for Windows Engine

- products/linux/14.0/guide/index.php
- products/linux/14.0/reference/index.php
- products/web/14.0/index.php
- products/web/web.config
- web.config
Change current-version to 14.0 which will be reflected on help.keyman-staging.com site.
Also update Linux content to 14.0 and seed web 14.0 page
> modify: Change current-version to 14.0

- developer/cloud/model_info/1.0/index.php
- developer/cloud/package-version/1.0/index.md
Relates to keymanapp/api.keyman.com#105.
> fix: cloud docs model_info and package-version

- products/desktop/web.config
- products/index.php
> fix: broken link for Desktop version history

- .github/workflows/ci.yml
- _includes/header.php
- _includes/includes/head.php
- _includes/includes/renderLanguageExample.php
- _includes/kmdisthtml.php
- developer/engine/web/1.0/content/index.php
- developer/engine/web/1.0/sub/editdesign.php
- developer/engine/web/10.0/reference/core/focusLastActiveElement.php
- developer/engine/web/11.0/reference/core/focusLastActiveElement.php
- developer/engine/web/12.0/reference/core/focusLastActiveElement.php
- developer/engine/web/13.0/reference/core/focusLastActiveElement.php
- developer/engine/web/2.0/reference/core/focusLastActiveElement.php
- keyboard/hieroglyphic/1.0/hieroglyphic.php
- keyboard/hieroglyphic/1.1/hieroglyphic.php
- keyboard/isis_gujarati/2.0.1/isis_gujarati.php
- keyboard/isis_gurmukhi/2.0.1/isis_gurmukhi.php
- keyboard/isis_kannada/2.0.1/isis_kannada.php
- keyboard/isis_oriya/2.1/isis_oriya.php
- keyboard/isis_telugu/2.0.1/isis_telugu.php
- products/desktop/6.0/main/about.php
Fixes #196.
Many of these pages are old but this will resolve page errors in any case and get us closer to clean CI reports.
> fix: various php errors

- developer/engine/web/14.0/reference/interface/contextExOutput.md
- developer/engine/web/14.0/reference/interface/index.php
> fix: add KCXO statement

- developer/engine/web/14.0/guide/examples/__auto-control.php
- developer/engine/web/14.0/guide/examples/__control-by-control.php
- developer/engine/web/14.0/guide/examples/__first-example.php
- developer/engine/web/14.0/guide/examples/__full-manual-control.php
- developer/engine/web/14.0/guide/examples/automatic-control.php
- developer/engine/web/14.0/guide/examples/control-by-control.php
- developer/engine/web/14.0/guide/examples/full-manual-control.php
- developer/engine/web/14.0/guide/examples/js/laokeys_load.js
- developer/engine/web/14.0/guide/examples/js/unified_loader.js
- developer/engine/web/14.0/guide/examples/manual-control.php
- developer/engine/web/14.0/guide/get-started.php
An... inverted(?) 🍒-pick of #290 targetting KMW 14.0's staging section.
> chore: reworks KMW examples to use init's Promise

- developer/engine/web/13.0/guide/examples/__auto-control.php
- developer/engine/web/13.0/guide/examples/__control-by-control.php
- developer/engine/web/13.0/guide/examples/__first-example.php
- developer/engine/web/13.0/guide/examples/__full-manual-control.php
- developer/engine/web/13.0/guide/examples/automatic-control.php
- developer/engine/web/13.0/guide/examples/control-by-control.php
- developer/engine/web/13.0/guide/examples/full-manual-control.php
- developer/engine/web/13.0/guide/examples/js/laokeys_load.js
- developer/engine/web/13.0/guide/examples/js/unified_loader.js
- developer/engine/web/13.0/guide/examples/manual-control.php
- developer/engine/web/13.0/guide/get-started.php
Addresses the 'documentation' aspect of https://github.com/keymanapp/keyman/issues/4143.
> change: reworks KMW examples to use init's Promise

- _common/KeymanHosts.php
- _includes/includes/head.php
* Harmonize KeymanHosts.php with keyman.com
* Exclude staging site from search engines
> chore: hosts and header maintenance

- developer/language/guide/expansions.md
- developer/language/guide/history.md
- developer/language/guide/index.php
- developer/language/reference/casedkeys.md
- developer/language/reference/index.php
Goes with keymanapp/keyman#4584 and keymanapp/keyman#4586.
> docs: expansions and CasedKeys store

- _includes/md/mdhost.php
> fix: markdown header parser was not parsing some headers 🍒

- knowledge-base/kb0105.md
- knowledge-base/kb0106.md
Two knowledge base articles:
* KMKB0105: INFO: Potential issues when upgrading to Keyman for Windows 14 with custom language profiles
* KMKB0106: HOWTO: Download a single keyboard folder from the Keyboards repository
> docs: keyman 14 upgrade and keyboard source download KBs

- _includes/includes/phone-menu.php
- cdn/dev/css/template.css
- developer/engine/web/14.0/reference/osk/index.php
- developer/engine/web/14.0/reference/osk/restorePosition.md
Relates to keymanapp/keyman#4946.
> docs(web): osk.restorePosition()

- developer/engine/web/14.0/reference/osk/setRect.php
> fix: `setRect` parameter mismatch for `nosize` and `nomove`

- developer/14.0/reference/file-types/kps.php
Fixes #247 updating Developer string details for kps.
Localization seems N/A for 14.0?
> fix: Update developer kps string details

- developer/cloud/search/2.0/index.md
Related PRs:
* keymanapp/api.keyman.com#151
* keymanapp/keyman.com#298
* keymanapp/help.keyman.com#389
> docs: add new totalDownloads property

- developer/keyboards/_shared/organize-folder-structure.php
- developer/keyboards/github/step-0.md
- developer/language/guide/us-english.php
> docs: add keyboard copyright advice

- developer/keyboards/github/step-0.md
@MakaraSok Does this clarification help?
> clarify keyboard name standards

- products/linux/11.0/reference/km-package-install.php
- products/linux/12.0/reference/km-package-install.php
- products/linux/13.0/reference/km-package-install.php
- products/linux/14.0/reference/km-config.php
- products/linux/14.0/reference/km-package-install.php
See also https://github.com/keymanapp/keyman/issues/4419
> chore(linux): Fix two typos

- developer/language/guide/index.php
- developer/language/guide/rules.md
- developer/language/guide/virtual-keys.md
Ref https://github.com/keymanapp/keyman/pull/5456#issuecomment-879541930
> docs: improve virtual key documentation

- developer/keyboards/github/step-2.md
Via private feedback on confusion on steps for submitting keyboard.
> docs: tweak instructions on how to drag files to github

- _includes/includes/com.keyman.help.editpage.inc.php
> fix: edit product help links

- developer/cloud/index.md
- developer/cloud/search/2.0/index.md
> docs: search query tweaks

- .gitignore
- Readme.md
(Also, add node_modules/ to .gitignore -- may be required later)
> docs: Add setup note for composer

- developer/keyboards/github/step-3.md
Based on feedback from Kent S. who felt the instructions didn't tell him how to finish the process.
> Add to GH submission procedure

- developer/15.0/context/keyboard-editor.php
- developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.php
- developer/engine/web/15.0/reference/layoutspec.php
- developer/language/guide/history.md
- developer/language/guide/virtual-keys.md
Relates to keymanapp/keyman#2858.
Documentation for this feature change, allowing for `U_1234_1235_1236[_...]` key identifiers.
> feat: u_xxxx_yyyy key identifiers

- developer/language/guide/virtual-keys.md
- developer/language/reference/casedkeys.md
Relates to keymanapp/keyman#5460.
Tweak documentation around Caps Lock use with KeymanWeb.
> docs: keymanweb and `&CasedKeys`

- developer/14.0/guides/lexical-models/advanced/search-term-to-key.php
Per discussion and bug discovery with Ron Lockwood
> docs: Update search-term-to-key.php

- knowledge-base/kb0104.md
Change from PostEvent to All for tccutil, based on experience in the team.
> chore: Update kb0104.md PostEvent to All for tccutil

- developer/14.0/guides/lexical-models/tutorial/step-3.php
Jeff Heath provided a link to the official web page for Primer Prep
> Correct the link to PrimerPrep software

- developer/language/guide/history.md
> chore: use statement order

- developer/engine/android/14.0/index.php
- developer/engine/android/15.0/KMManager/advanceToNextInputMode.md
- developer/engine/android/15.0/KMManager/advanceToPreviousInputMethod.md
- developer/engine/android/15.0/KMManager/canAddNewKeyboard.php
- developer/engine/android/15.0/KMManager/canRemoveKeyboard.md
- developer/engine/android/15.0/KMManager/index.php
- developer/engine/android/15.0/KMManager/setCanAddNewKeyboard.php
- developer/engine/android/15.0/index.php
This updates some of the Keyman Engine for Android KMManager content for 15.0
> docs: Update Keyman Engine Android docs for 15.0

- developer/language/guide/virtual-keys.md
Fixes #522 in documenting U_xxxx_yyyy in virtual keys guide.
> chore: Document U_xxxx_yyyy in virtual keys guide

- developer/engine/web/14.0/reference/core/getKeyboard.php
Documents the features added by https://github.com/keymanapp/keyman/pull/6567.
> feat: adds new properties for Web's getKeyboard API

- developer/engine/android/15.0/KMManager/getHapticFeedback.md
- developer/engine/android/15.0/KMManager/index.php
- developer/engine/android/15.0/KMManager/setHapticFeedback.md
Documents the Keyman for Android haptic feedback feature added in keymanapp/keyman#6626
> chore: document Android haptic feedback

- keyboard/redir.php
> fix: use version sort for keyboard help redirection

- developer/15.0/guides/distribute/packages.php
> docs: add note on cloud services for distribution

- developer/engine/iphone-and-ipad/15.0/guides/system-keyboard/index.php
- developer/engine/iphone-and-ipad/15.0/index.php
> fix: updates 15.0 ios sys kbd guide

- developer/core/desktop/16.0/building.php
- developer/core/desktop/16.0/c-api/context-api.php
- developer/core/desktop/16.0/c-api/index.php
- developer/core/desktop/16.0/c-api/keyboard-api.php
- developer/core/desktop/16.0/c-api/option-api.php
- developer/core/desktop/16.0/c-api/state-api.php
- developer/core/desktop/16.0/index.php
- developer/core/desktop/16.0/json-schema.php
Note: first commit just seeds the 16.0 Core docs.
> docs(core): add km_kbp_event function

- developer/16.0/guides/develop/tutorial/index.php
- developer/16.0/guides/develop/tutorial/step-1.php
- developer/16.0/guides/develop/tutorial/step-2.php
- developer/16.0/guides/develop/tutorial/step-3.php
- developer/16.0/guides/develop/tutorial/step-4.php
- developer/16.0/guides/develop/tutorial/step-5.php
- developer/16.0/guides/develop/tutorial/step-6.php
- developer/16.0/guides/develop/tutorial/step-7.php
- developer/16.0/guides/develop/tutorial/step-8.php
- developer/16.0/guides/develop/tutorial/step-9.php
Fixes issue described in #611 for Developer 16.0.
> fix: links to tutorial steps

- resources/builder.inc.sh
This updates the repo's copy of the common builder script from 16.0 beta
> chore: Update builder.inc.sh

- _includes/includes/servervars.php
- developer/15.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
- developer/16.0/guides/develop/creating-a-touch-keyboard-layout-for-amharic-the-nitty-gritty.md
- developer/engine/web/10.0/reference/osk/classes.php
- developer/engine/web/11.0/reference/osk/classes.php
- developer/engine/web/12.0/reference/osk/classes.php
- developer/engine/web/13.0/reference/osk/classes.php
- developer/engine/web/14.0/reference/osk/classes.php
- developer/engine/web/15.0/reference/osk/classes.php
- developer/engine/web/16.0/reference/osk/classes.php
- developer/engine/web/2.0/guide/get-started.php
- developer/engine/web/2.0/reference/osk/classes.php
> fix: update s.keyman.com refs to https

- Readme.md
- resources/kubectl/help-kubectl.yaml
This is both shorter and less of a potential error magnet than a custom bash script.
> Convert custom init git fetch script to use git-sync instead

- resources/kubectl/help-kubectl-deploy.yaml
- resources/kubectl/help-kubectl.yaml
Remove webhook match on non-existant keys in payload object. Fix issue with deployer script getting stuck, due to missing `--depth` flag, incorrect `git reset` invocation.
Add TLS object to ingress for dpeloyment manifest.
> Fix various issues related to the api/deploy webhook

- .github/workflows/cleanup.yml
- .github/workflows/docker.yaml
Build and push an image to the ghcr
> Create docker.yaml to build customised PHP runtime

- developer/cloud/1.0/webapi.php
- developer/cloud/2.0/index.php
- developer/cloud/3.0/index.php
- developer/cloud/4.0/index.php
- developer/cloud/keyboard_info/1.0/index.php
I didn't wait for the CI to complete in #720 and missed these links which needed updating.
> fix: marc broke the site

- build.sh
- resources/builder.inc.sh
Incorporates udpates from other site work:
* Update builder.inc.sh
* Assign a name "help-keyman-com-app" to the Docker container
> epic: Add Docker container name 🦭

- .github/workflows/docker.yml
- resources/kubectl/help-kubectl.yaml
- Removes build.sh configure from k8s step
- Adds it to docker action instead
- Also fixes the image for k8s app-php
> chore: do build.sh configure in docker action

- knowledge-base/kb0110.md
> docs:  Add TSF knowledge base page

- .github/workflows/auto-approve-keyman-server-pr.yml
- .github/workflows/auto-merge-keyman-server-pr.yml
- keyboard/fv_dene_zhatie/10.0/fv_dene_zhatie.php
Note: we may move to using GitHub's auto-merge functionality in the future, but this is lower friction for now (https://cli.github.com/manual/gh_pr_merge this may make this simple with `gh pr merge --auto`)
See also https://github.com/keymanapp/keyboards/pull/2416
> chore: auto PR merge after CI finished

- .github/workflows/auto-approve-keyman-server-pr.yml
- .github/workflows/auto-merge-keyman-server-pr.yml
Updates action versions, sets some delays for merge (because it was happening too quickly), cleans up yaml
> chore: tweak auto merging

- .htaccess
Addresses the point on keymanapp/keyman.com#403
>  * http -> https upgrade on staging and production -- verify no needless .htaccess rules
> chore: Remove redirect for live site 🦭

- resources/init-container.sh
Relates to keymanapp/keyman#403
> CDN refresh in init-container.sh
> fix: Add cdnrefresh to init-container.sh

- .htaccess
> chore: Cleanup unused .htaccess comments

- knowledge-base/kb0039.md
This allows the "Previous article" and "Next article" breadcrumbs to continue.
> chore: Add placeholder for kb0039.md

- .htaccess
:cherries: pick #988 from staging to master
> chore: cherrypick -- Cleanup unused .htaccess comments

- .htaccess
- _includes/includes/index-content.php
- _includes/kmdev.php
- _includes/kmdevhtml.php
- _includes/kmdist.php
- _includes/kmdisthtml.php
- _includes/kmdistrtf.php
- _includes/kmhelp.php
- _includes/kmhelphtml.php
- build.sh
- cdn/dev/css/template.css
Cleanup the infrastructure for the new API documentation for kmc modules coming soon. Relates to keymanapp/keyman#10207.
Will add links once the first automatic deploy of kmc api docs lands
> docs: infrastructure around the kmc API documentation 📚

- developer/17.0/reference/kmc/cli/reference.md
> docs(developer): `kmc message` reference

- developer/language/reference/baselayout.md
> fix: restore baselayout documentation

- _includes/includes/head.php
- _includes/includes/index-content.php
> fix: escape entities in left-hand menu and title

- developer/17.0/index.md
- developer/17.0/whats-new.md
> docs(developer): Add What's New page

- developer/engine/web/16.0/reference/core/setKeyboardForControl.php
- developer/engine/web/17.0/reference/core/setKeyboardForControl.php
> chore: updates docs for setKeyboardForControl (16.0 + 17.0)

- developer/17.0/whats-new.md
Missed a couple of dot points in what is new with 17.0.
> chore(developer): Update whats-new.md

- developer/language/reference/_index.md
> chore: mobile and web using index() information

- developer/language/reference/version.md
Updates with information about version store being optional since v10.0...
> docs: Update version.md

- _includes/includes/head.php
Relates to keymanapp/keyman#11467.
> fix: temporarily roll back to keymanweb 16.0.147

- _includes/includes/kb_doc_template.php
Fixes: #806
Please check the KeymanHosts link. 
It was not linking to keyman.com and it might be that I'm on localhost.
> feat: keyboard help files now have keyboard download links

- developer/17.0/reference/file-layout.md
> docs: update title of file-layout.md

- developer/17.0/whats-new.md
fixes https://github.com/keymanapp/keyman/issues/11748
> docs: Add windows-package-installer notes to whats-new.md

- developer/17.0/guides/distribute/packages.md
> docs: add a link to packages.md

- developer/keyboards/starter/step-4.md
> chore: update step-4.md

- Readme.md
Just clarifying the setup steps for running the site locally.
> chore: Update install steps in README

- knowledge-base/kb0072.md
> chore: Update link in kb0072.md

- _includes/includes/head.php
- cdn/dev/js/kbd-docs.js
Reverts keymanapp/help.keyman.com#1272 per keymanapp/keyman#12345
> chore: Revert "change: use published Keyman Engine API to fetch keyboards in keyboard help pages"

- developer/language/reference/any.md
- developer/language/reference/notany.md
Ref https://community.software.sil.org/t/is-notany-fully-interchangeable-with-any/9098/3
> docs: tweak any and notany docs for clarity

- .gitignore
- .htaccess
- .user.ini
- Readme.md
- build.sh
- developer/language/guide/virtual-keys.md
Relates-to: keymanapp/keyman.com#494
Depends-on: keymanapp/shared-sites#38
> chore: support debug flag for error logging

- developer/keyboards/advanced/step-0.md
Per https://github.com/keymanapp/keyboards/pull/3241#issuecomment-2519009194
> docs: clarify MIT license documentation

- build.sh
- cdn/dev/css/template.css
* v0.12 of shared-sites
* adds CSS for GFM-style alerts to render nicely
> feat: move to GFM-style alerts

- knowledge-base/index.php
> feat: add alerts to knowledge base pages

- .htaccess
- developer/10.0/guides/distribute/tutorial/step-4.php
- developer/11.0/guides/distribute/tutorial/step-4.php
- developer/12.0/guides/distribute/tutorial/step-4.php
- developer/13.0/guides/distribute/tutorial/step-4.php
- developer/14.0/guides/distribute/tutorial/step-4.php
- developer/15.0/guides/distribute/tutorial/step-4.php
- developer/16.0/guides/distribute/tutorial/step-4.php
More on: https://github.com/keymanapp/keyman.com/issues/415.
I found some of this `www.keyman.com` in Google Console, but still don't know where the URLs came from.
Descriptive reports: https://docs.google.com/spreadsheets/d/1On3WrJMyDo3QboQvl7S1sbtD1z3HO3JH/edit?usp=sharing&ouid=115939244027961768677&rtpof=true&sd=true
> chore: changes to use https and fix linking

- developer/11.0/context/kmcomp.php
- developer/12.0/context/kmcomp.php
- developer/13.0/context/kmcomp.php
- developer/14.0/context/kmcomp.php
- developer/15.0/context/kmcomp.php
- developer/16.0/context/kmcomp.md
Continue: https://github.com/keymanapp/keyman.com/issues/415
From: #1771
> chore: fixes broken internal URLs

- build.sh
Relates-to: #1791
Depends-on: keymanapp/shared-sites#51
> chore: upgrade to shared v0.15

- products/android/10.0/index.php
- products/android/2.0/index.php
fixes: #1788.
This PR is ready for reviews.
> chore: fixes broken internal URLs in `products/android/`

- developer/index.php
- index.php
- keyboard/index.php
- products/index.php
fixes: #1790 
This PR is ready for reviews.
> chore: changes h2 to h1 tags

- developer/engine/android/15.0/index.php
- developer/keyboards/github/step-2.md
Fix: https://github.com/keymanapp/keyman/issues/12898.
This PR is ready for reviews.
> chore: adjust anchor and bookmark link

- cdn/dev/css/template.css
- developer/index.php
- index.php
- keyboard/index.php
- products/index.php
> fix: replace center tags with major-title classes for h1 tags, and styling

- _includes/includes/__kmwheader.php
- _includes/includes/servervars.php
- developer/engine/web/1.0/tutorial.php
Also removed $site_securetavultesoft and $downloadsDomain.
Fixes: #1870
> refactor: remove use of old $TestServer variable

- developer/keyboards/phphelpfile.md
I have suggested some small clarifications, based on my experience of using this tutorial for PR keymanapp#3354. In particular, giving a fuller list of what HTML tags to delete and how to embed the CSS inside the `<?PHP ?>` tag. (I also split step 5 into two steps, and hence following steps have been renumbered.)
> Small clarifications to phphelpfile.md

- developer/language/reference/_nul.md
Relates-to: keymanapp/keyman#13455
Relates-to: keymanapp/keyman#13532
> docs(developer): clarify usage of `nul` statement in rule output

- .htaccess
Updates current-version and latest-version with the stable-18.0 release
> Update current-version to 18.0 and latest-version to 19.0

- developer/language/reference/if.md
Add the names of two additional system stores used in if()
> Add `newlayer` and `oldlayer` store info to if.md

- developer/language/reference/index.md
> docs: move deprecated statements to separate section

- _includes/includes/com.keyman.help.editpage.inc.php
- _includes/includes/footer.php
Also notes difficulties for editing keyboards and alternate way of storing metadata to make determining path to edit easier to find.
Fixes: #2080
> fix: edit correct page for developer, engine help

- developer/language/reference/_keywordsbytype.md
- developer/language/reference/index.md
> chore: polish alerts and remove span tags

- knowledge-base/kb0106.md
Inspired from https://community.software.sil.org/t/how-to-update-keyboard-without-cloning-the-entire-repository/9793/2
> chore: add download shared font folder and use alerts

- developer/language/reference/deadkey.md
I don't want the example from https://community.software.sil.org/t/how-can-we-set-branch-transformation-in-keyman/9771/4 get lost.
> chore: additional deadkey example from community site

- knowledge-base/kb0101.md
- knowledge-base/kb0102.md
This brings the comments from PR #2152.
> docs(linux): addressing review comments on #2152

- developer/language/reference/_index.md
> docs: fix error of index() rule example

- developer/language/reference/version.md
Documentation corresponds to https://github.com/keymanapp/keyman/pull/11957
See also https://github.com/keymanapp/keyboards/pull/3663#issuecomment-3173175227
Test-bot: skip
> docs: Update multi-part Unicode identifiers version restriction note for Developer 18.0

- developer/language/reference/index.md
> Change .kvk to .kvks for &VisualKeyboard

- developer/language/guide/control-keys.md
- developer/language/guide/groups.md
- developer/language/guide/index.md
- developer/language/guide/virtual-keys.md
Relates-to: keymanapp/keyman#14148
Test-bot: skip
> docs: add Control keys and control characters guide
